name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: Sync
            uses: repo-sync/github-sync@v2
            with:
            source_repo: 'https://github.com/TBXark/ChatGPT-Telegram-Workers'
            target_repo: 'https://github.com/shadoway11/ChatGPT-Telegram-Workers‘
            github_token: ${{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}} 
            source_branch: 'master'
